onlyBuiltDependencies:
  - esbuild

overrides:
  '@babel/helpers@<7.26.10': '>=7.26.10'
  '@octokit/endpoint@>=10.0.0 <10.1.3': '>=10.1.3'
  '@octokit/plugin-paginate-rest@>=9.3.0-beta.1 <11.4.1': '>=11.4.1'
  '@octokit/request-error@>=6.0.0 <6.1.7': '>=6.1.7'
  '@octokit/request@>=9.0.0-beta.1 <9.2.1': '>=9.2.1'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  braces@<3.0.3: '>=3.0.3'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  esbuild@<=0.24.2: '>=0.25.0'
  micromatch@<4.0.8: '>=4.0.8'
  semver@>=6.0.0 <6.3.1: '>=6.3.1'
